include(FindPackageHandleStandardArgs)

find_path(SODIUM_INCLUDE_DIR NAMES sodium.h)
find_library(SODIUM_LIBRARIES NAMES sodium)
mark_as_advanced(SODIUM_INCLUDE_DIR SODIUM_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(Sodium
    REQUIRED_VARS SODIUM_LIBRARIES SODIUM_INCLUDE_DIR
)
